### ISSUE TITLE
Fails to build on Windows.

### ISSUE THREAD

**Issue by JonathanBerkeley** [epacke/logstash-pipeline-tester#150]
When running "docker compose build" on Windows, it fails on the step "RUN npm run build", see output below:

<details open>
  <summary>Error log</summary>
 
  ### 

```
 => [pipeline-ui compile-image  9/14] COPY ./frontend/ /home/node/app/frontend                        0.0s
 => [pipeline-ui compile-image 10/14] WORKDIR /home/node/app/frontend                                 0.0s
 => ERROR [pipeline-ui compile-image 11/14] RUN npm run build                                        65.0s
------
 > [pipeline-ui compile-image 11/14] RUN npm run build:
#0 0.762
#0 0.762 > logstash-pipeline-tester-ui@0.1.0 build
#0 0.762 > react-scripts build
#0 0.762
#0 2.064 Creating an optimized production build...
#0 64.78 Failed to compile.
#0 64.78
#0 64.79 [eslint]
#0 64.79 src/App.tsx
#0 64.79   Line 1:50:   Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
#0 64.79   Line 2:37:   Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
#0 64.79   Line 3:37:   Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

<Error continues for hundreds of lines for each .ts, tsx and .js file.>

#0 64.79
#0 64.79 Search for the keywords to learn more about each error.
#0 64.79
#0 64.79
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```
</details>

There was hundreds of "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style" errors for each file so I replaced this in the log with "<Error continues for hundreds of lines for each .ts, tsx and .js file.>".

I tried to also run it in Ubuntu in WSL2 (still using Windows filesystem), to the same error.

**Comment by epacke** [comment]
Thanks for reporting!
I'll try to reproduce this. Will get back to you.

**Comment by epacke** [comment]
Managed to reproduce it and fixed it. Look here on how to solve it on your local repo:
https://github.com/epacke/logstash-pipeline-tester/pull/153

Thanks again for reporting, I bet this stumped a few people.

**Comment by JonathanBerkeley** [comment]
Great, thanks!
