### ISSUE TITLE
UI is not able to detect pipeline broken down in multiple files

### ISSUE THREAD

**Issue by anubisg1** [epacke/logstash-pipeline-tester#74]
as per title, when a pipeline is broken down in multiple files, the following happens to the UI

mounted as
```
    volumes:
      - "./logstash/logstash-config/inputs:/usr/src/pipeline/input"
 ``` 

![image](https://user-images.githubusercontent.com/4518931/207283272-24e1d6d0-78f3-4a03-88bb-0b156b38f4b1.png)

logstash example config:

pipelines.yml
```
############### INPUTS ###############
- pipeline.id: inputs
  path.config: "/usr/share/logstash/config/inputs/{*}.conf"
```

00_inputs.conf
```
input {

}
```

01_filter1.conf
```
filter {

}
```

02_filter2.conf
```
filter {

}
```

03_output.conf
```
output {

}
```

**Comment by epacke** [comment]
Have you tried the latest version?

**Comment by anubisg1** [comment]
> Have you tried the latest version?

of course you fixed it between a commit 2 weeks ago and now :D 

Thank you!

**Comment by epacke** [comment]
Chu chu, here goes the dev train! 😂
